import Image from 'next/image';
import Link from 'next/link';
import './globals.css'
import { Inter } from 'next/font/google'
import EmailIcon from"../../public/email-icon.svg"
import GithubIcon from"../../public/github.svg"
import LinkedinIcon from"../../public/linkedn.svg"
import TwiterIcon from"../../public/twiter.svg"
import WhatsappIcon from"../../public/whatsapp.svg"
import YoutubIcon from"../../public/youtube.svg"
import Menu from "./Menu.js"

const inter = Inter({ subsets: ['latin'] })
const liStyle = 'list-none no-underline font-semibold text-base mr-5 mt-5 ml-5';
const footerIconStyle = "inline-flex text-grey mx-20 py-2";
const footerTextStyle = "px-4"



export const metadata = {
  title: 'Protofolio',
  description: 'Generated by create next app',
}




export default function RootLayout({ children }) {


  return (

    <html lang="en">
      <body className={inter.className}>

        <header className='flex w-full h-14 opacity-90 bg-grey text-black border border-black rounded-lg fixed blur-none'>

          <h1 className='flex-1 text-xl font-bold ml-6 mt-4'>Anuj Kumar</h1>

          <nav className=''>
            <ul className='flex justify-around'>

              <li className={liStyle}>
                <p>Dashborard</p>
              </li>
              <li><Menu /></li>
            </ul>

          </nav>
        </header>
        
        <div className='px-10 bg-grey'>
          {children}
        </div>
        
        <footer id='footer-contact' className='bg-browen rounded-t-xl '>
          <h2 className="text-grey text-2xl font-bold px-28 py-3 "> Contacts</h2>
          <ul >
            <li >
              <Link className={footerIconStyle} href={"#"}>
                <Image src={EmailIcon}></Image>
                <p className={footerTextStyle}>Email</p>
              </Link>
              </li>
            <li>
              <Link href={"#"} className={footerIconStyle}>
                <Image src={WhatsappIcon}></Image>
                <p className={footerTextStyle}>Whatsapp</p>
              </Link>
            </li>
            <li>
              <Link href={"#"} className={footerIconStyle}><Image src={LinkedinIcon}></Image>
                <p className={footerTextStyle}>Linkedin</p>
              </Link>
            </li>
            <li>
              <Link href={"#"} className={footerIconStyle}>
                <Image src={GithubIcon}></Image>
                  <p className={footerTextStyle}>GitHub</p>
              </Link>
            </li>
            <li>
              <Link href={"#"} className={footerIconStyle}>
                <Image src={TwiterIcon}></Image>
                <p className={footerTextStyle}>Twitter</p>
              </Link>
            </li>
            <li>
              <Link href={"#"} className={footerIconStyle}>
                <Image src={YoutubIcon}></Image>
                <p className={footerTextStyle}>YouTube</p>
              </Link>
            </li>
          </ul>

        </footer>
      </body>
    </html>

  )
}
