import Image from 'next/image';
import Link from 'next/link';
import './globals.css'
import { Inter } from 'next/font/google'
import EmailIcon from"../../public/email-icon.svg"
import GithubIcon from"../../public/github.svg"
import LinkedinIcon from"../../public/linkedn.svg"
import tweetIcon from"../../public/twiter.svg"

const inter = Inter({ subsets: ['latin'] })
const liStyle = 'mr-10 decoration-wavy decoration-sky-500 hover:underline ';
const footerIconStyle = "inline-flex -ml-10 my-2";
const footerTextStyle = "mx-2 pt-1 pl-2"



export const metadata = {
  title: 'Protofolio',
  description: 'Generated by create next app',
}




export default function RootLayout({ children }) {


  return (

    <html lang="en">
      <body className={inter.className}>

        {/* navbar start */}
        <nav className="font-sans text-lg bg-slate-100 flex w-full h-12 shadow-2xl fixed border">
        <h1 className="text-4xl font-bold ml-6 me-64">AK</h1>

        <div className=" flex justify-between font-normal">
            <ul className="flex ml-24 my-2">
                <li className="ml-56 pl-20 mr-10 decoration-wavy decoration-sky-500 hover:underline "><Link href="/">Home</Link></li>
                <li className={liStyle}><Link href="/About">About</Link></li>
                <li className={liStyle}><Link href="/Blogs">Blogs</Link></li>
                <li className={liStyle}><Link href="/Workshop">Workshop</Link></li>
                <li className={liStyle}><Link href="/#footer-contact">Contact</Link></li>
            </ul>

            <div className="">
                <button className= 'ml-10 my-2 border-2 border-current hover:bg-sky-200 w-20 rounded-full' type="button">Setting</button>
            </div>
        </div>
    </nav>
        
        {/* navbar end here */}


        {/* main boody put her */}
        <div className=''>
          {children}
        </div>


        {/* footer start here */}
        <footer id='footer-contact' className='bg-black text-white pl-56 pt-5'>
          <div className='ml-40 pl-40 border-black border-4 justify-centre'>
            <h2 className="text-white text-2xl font-semibold tracking-wide mb-2"> Contacts</h2>
            <ul className=''>
              <li>
                <Link className={footerIconStyle} href={"mailto:kumaranuj154000@gmail.com"}>
                  <Image src={EmailIcon} alt='email'></Image>
                  <p className={footerTextStyle}>Email: kumaranuj154000@gmail.com</p>
                </Link>
                </li>
              <li>
                <Link href={"#"} className={footerIconStyle}>
                  <Image src={tweetIcon} alt='twitter'></Image>
                  <p className={footerTextStyle}>Twitter or X </p>
                </Link>
              </li>
              <li>
                <Link href={"https://www.linkedin.com/in/anuj-kr-vandium-915880194/"} className={footerIconStyle}>
                <Image src={LinkedinIcon} alt='Linkedin'></Image>
                <p className={footerTextStyle}>Linkedin</p>
                </Link>
              </li>
              <li>
                <Link href={"https://github.com/anujkumar-t9"} className={footerIconStyle}>
                  <Image src={GithubIcon} alt='Github'></Image>
                    <p className={footerTextStyle}>GitHub</p>
                </Link>
              </li>
            </ul>
          </div>
        </footer>
        {/* footer end here */}

      </body>
    </html>

  )
}
